FROM mysql:8.0.33

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin
ENV MYSQL_DATABASE=mydatabase

# Expose the default MySQL port
EXPOSE 3306